### ISSUE TITLE
Add ImgBot

### ISSUE THREAD

**Issue by Matt-Gleich** [hackclub/assets#1]
ImgBot is a lossless compression bot for images. So it can reduce the size of images without changing the quality. Here is a link:

https://imgbot.net/

If some pricing issue comes up I'm sure the guy who makes it would give us a discount/for free. Also this can be applied for the entire organization, or just this repo.

**Comment by lachlanjc** [comment]
Thanks! Just added. Hasn’t done anything yet though.
